FROM ubuntu:20.04

ARG CXXFLAGS="-DSTACK_TRACE:BOOL -DELPP_FEATURE_CRASH_LOG"
ARG HAVEN_VERSION=v2.2.3
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG USE_SINGLE_BUILDDIR=1
ARG DEBIAN_FRONTEND=noninteractive
ARG ZMQ_VERSION: v4.3.1
ARG CPPZMQ_VERSION: v4.3.0
ARG CFLAGS: -fPIC
ARG CXXFLAGS: -fPIC

RUN apt-get update && apt-get --no-install-recommends --yes install ca-certificates git wget libcurl4-openssl-dev build-essential cmake pkg-config libssl-dev libunbound-dev libsodium-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev libudev-dev

RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz \
    && tar -xvf boost_1_77_0.tar.gz \
    && cd boost_1_77_0 \
    && ./bootstrap.sh \
    && ./b2 install -j3

RUN git clone https://github.com/zeromq/libzmq.git -b ${ZMQ_VERSION} \
    && cd libzmq \
    && ./autogen.sh \
    && ./configure --enable-static --disable-shared \
    && make -j3 \
    && make install \
    && ldconfig

RUN git clone https://github.com/zeromq/cppzmq.git -b ${CPPZMQ_VERSION} \
    && cd cppzmq \
    && mv *.hpp /usr/local/include
    
COPY . /haven-main
WORKDIR /haven-main
RUN git submodule update --init --force
RUN if [ "$TARGETARCH" = "amd64" ]; then export build=x86_64; fi; \
if  [ "$TARGETARCH" = "386" ]; then export build=i686; fi; \
if [ "$TARGETARCH" = "arm" ]; then export build=${TARGETARCH}${TARGETVARIANT}; fi; \
if [ "$TARGETARCH" = "arm64" ]; then export build=armv8; fi; \
make release-static-${TARGETOS}-${build} 

RUN build/release/bin/havend --version
